project:
  type: website
  output-dir: docs

filters:
  - shinylive

website:
  title: "FINTECH 533"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
